// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeSX0g0F5ePQcAUjghWgKKvFZRrEnvVTY',
    appId: '1:303150588473:web:d345914306502ba6a463e8',
    messagingSenderId: '303150588473',
    projectId: 'gamebook-8fe52',
    authDomain: 'gamebook-8fe52.firebaseapp.com',
    storageBucket: 'gamebook-8fe52.appspot.com',
    measurementId: 'G-CY9VDRY6GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3L0DNLvqHO9X15zZ9u3i7PnBwa1FfAY',
    appId: '1:303150588473:android:fd7680b41c22a82aa463e8',
    messagingSenderId: '303150588473',
    projectId: 'gamebook-8fe52',
    storageBucket: 'gamebook-8fe52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUKTpUS-2ec3OqC3X-hLYAygSrjocAN3o',
    appId: '1:303150588473:ios:98f4d046c292602da463e8',
    messagingSenderId: '303150588473',
    projectId: 'gamebook-8fe52',
    storageBucket: 'gamebook-8fe52.appspot.com',
    androidClientId: '303150588473-k5h9rckgevjlincv6op39ucesu4u0smu.apps.googleusercontent.com',
    iosClientId: '303150588473-ou90561u4p2dkgvftu7d8utsqkbjf4bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUKTpUS-2ec3OqC3X-hLYAygSrjocAN3o',
    appId: '1:303150588473:ios:b07acd6389e6c95da463e8',
    messagingSenderId: '303150588473',
    projectId: 'gamebook-8fe52',
    storageBucket: 'gamebook-8fe52.appspot.com',
    androidClientId: '303150588473-k5h9rckgevjlincv6op39ucesu4u0smu.apps.googleusercontent.com',
    iosClientId: '303150588473-gitru04ght0e3jklbgq78gp64sgaetla.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameBook.RunnerTests',
  );
}
